In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib as mpl

In [3]:
# 그림의 폰트 사이즈 설정
label_size = 14
mpl.rcParams['xtick.labelsize'] = label_size 
mpl.rcParams['ytick.labelsize'] = label_size

In [12]:
# input data
data = np.array([0,0,3,4,5,0])

In [13]:
# filter
conv1d_filter = np.array([1,2,3])

In [10]:
def Conv1D_Numpy(Seq, Kernel):
    kernel_size = len(Kernel)
    Length = len(Seq)
    
    output = []
    for i in range(Length-kernel_size+1):
        conv = np.dot(Seq[i:i+kernel_size], Kernel)
        print(Seq[i:i+kernel_size], '*', Kernel, '->', conv)
        
        output.append(conv)
    
    output = np.array(output)
    
    return output

In [14]:
output = Conv1D_Numpy(data, conv1d_filter)
output

[0 0 3] * [1 2 3] -> 9
[0 3 4] * [1 2 3] -> 18
[3 4 5] * [1 2 3] -> 26
[4 5 0] * [1 2 3] -> 14


array([ 9, 18, 26, 14])